version: "3"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  redis:
    image: redis
    command: redis-server --requirepass example
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
